import { blue, green, neutral, red, yellow } from "./colors";
import { primaryFont } from "./typography";

export const lightTheme = {
  background: neutral[100],
  logo: neutral[800],
  header: neutral[100],
  switchColor: neutral[700],
  buttonTheme: {
    primaryColor: neutral[700],
    primaryHoverColor: neutral[500],
    textColorOnPrimary: neutral[700],
    // textColorOnPrimary: neutral[400],
  },
  primaryColor: yellow[200],
  primaryHoverColor: yellow[100],
  textColorOnPrimary: neutral[800],
  textColor: neutral[600],
  textColorInverted: neutral[100],
  formElementBackground: neutral[100],
  textOnFormElementBackground: neutral[600],
  primaryFont,
  status: {
    warningColor: yellow[100],
    warningColorHover: yellow[200],
    warningColorActive: yellow[300],
    errorColor: red[100],
    errorColorHover: red[200],
    errorColorActive: red[300],
    successColor: green[100],
    successColorHover: green[200],
    successColorActive: green[300],
  },
};

export const darkTheme = {
  background: neutral[800],
  logo: neutral[100],
  header: neutral[700],
  switchColor: neutral[600],
  buttonTheme: {
    primaryColor: neutral[200],
    primaryHoverColor: neutral[100],
    textColorOnPrimary: neutral[700],
  },
  primaryColor: red[400],
  primaryHoverColor: red[300],
  textColorOnPrimary: neutral[100],
  textColor: yellow[400],
  textColorInverted: neutral[100],
  primaryFont: primaryFont,
  disabled: neutral[400],
  textOnDisabled: neutral[300],
  formElementBackground: blue[100],
  textOnFormElementBackground: neutral[100],
  status: {
    warningColor: yellow[100],
    warningColorHover: yellow[200],
    warningColorActive: yellow[300],
    errorColor: red[100],
    errorColorHover: red[200],
    errorColorActive: red[300],
    successColor: green[100],
    successColorHover: green[200],
    successColorActive: green[300],
  },
};
